/* ───────────────────────────────────────────────────────────────────────────
 * CARA Authority Hub — shared types
 *
 * The server (/api/research) re-emits a clean, UI-shaped SSE protocol. The raw
 * TinyFish SSE (STARTED / STREAMING_URL / PROGRESS / COMPLETE / HEARTBEAT) is
 * parsed server-side and never reaches the browser directly.
 * ─────────────────────────────────────────────────────────────────────────── */

export type Phase = "ingest" | "misinfo" | "draft" | "done";

export type Severity = "UNVERIFIED" | "MINOR_DISCREPANCY";

/** A verified fact extracted from a pre-approved official source. */
export interface Finding {
  agency: string; // "MOH", "NEA", "WHO"
  stat?: string; // short headline number, e.g. "R0 1.42"
  text: string; // human-readable finding
  url?: string;
  timeAgo?: string; // "12 mins ago"
}

/** A consulted source (drives the "consulted N sources" chips). */
export interface SourceRef {
  name: string; // "MOH", "gov.sg", "NEA"
  url: string;
}

/** One step in how a claim propagated. */
export interface OriginEvent {
  date?: string;
  outlet: string; // platform / publisher
  event: string; // what happened
  type: "origin" | "amplification" | "debunk" | "investigation";
  url?: string; // link to the source article (clickable)
}

/** Traced origin & propagation of a misinformation claim (OpenAI web search). */
export interface ClaimOrigin {
  summary?: string; // optional one-liner (usually omitted — the timeline is the trace)
  originDate?: string;
  firstChannel?: string;
  singleSource?: boolean; // does everything trace to one source?
  timeline: OriginEvent[];
}

/** A published fact-check corroborating that a claim is false/misleading. */
export interface FactCheck {
  publisher: string;
  rating: string;
  title: string;
  url: string;
}

/** A questionable public claim, after OpenAI classification vs verified findings. */
export interface Claim {
  id: string;
  text: string; // the claim, verbatim-ish
  severity: Severity;
  where?: string; // "WhatsApp", "community forum"
  shares?: string; // "3.2k shares"
  contradicts?: string; // which official guidance it distorts
  analysis?: string; // CARA/OpenAI one-line assessment
  fix?: string; // suggested clarification point for a broadcast
  velocity?: string; // optional GDELT-style spread label: SURGING / RISING ...
  origin?: ClaimOrigin; // traced origin & propagation (added after the trace step)
  factChecks?: FactCheck[]; // corroborating published fact-checks
}

/** Real-world coverage signal from GDELT (the live half of misinfo intelligence). */
export interface Spread {
  velocityLabel: string; // global velocity: SURGING / RISING / STEADY / DECLINING / MINIMAL
  totalArticles: number; // global article/record count
  topCountries: string[];
  singaporeArticles: number; // articles mentioning Singapore
  singaporeVelocity: string; // Singapore-coverage velocity
  toneLabel?: string; // ALARMIST / NEGATIVE / NEUTRAL / POSITIVE (BigQuery only)
  avgTone?: number; // mean GDELT tone (negative = critical)
  source?: "bigquery" | "doc"; // which GDELT backend produced this
  timeline?: SpreadPoint[]; // daily coverage for trend charts
}

/** One day of coverage for the spread trend charts. */
export interface SpreadPoint {
  date: string; // YYYY-MM-DD
  global: number; // global article count that day
  sg: number; // Singapore-related count that day
  tone?: number; // mean tone that day (BigQuery)
}

/** The broadcast triage decision — the spine of the dashboard. */
export type Verdict = "BROADCAST" | "MONITOR" | "NO ACTION";
export interface Assessment {
  verdict: Verdict;
  rationale: string; // one short line
  urgency: "HIGH" | "NORMAL";
  audience: string; // suggested target, short
  signals: { local: string; spread: string; misinfo: string }; // compact one-liners
}

/** The caregiver-facing draft generated by OpenAI. */
export interface Draft {
  title: string; // "[URGENT: DENGUE ADVISORY]"
  body: string;
  target: string; // "Caregivers of elderly — East Region"
  urgency: "HIGH" | "NORMAL";
  checklist?: string[]; // separated add-on, not part of official message
}

/* ─── Server → client event protocol ──────────────────────────────────────── */

export type ServerEvent =
  | { type: "PHASE"; phase: Phase; label: string }
  | { type: "STREAMING_URL"; url: string }
  | { type: "LOG"; level: "info" | "warn" | "ok"; message: string; ts?: string }
  | { type: "SOURCE"; source: SourceRef }
  | { type: "FINDING"; finding: Finding }
  | { type: "CLAIM"; claim: Claim }
  | { type: "ORIGIN"; claimId: string; origin: ClaimOrigin }
  | { type: "FACTCHECK"; claimId: string; factChecks: FactCheck[] }
  | { type: "SPREAD"; spread: Spread }
  | { type: "ASSESSMENT"; assessment: Assessment }
  | { type: "DRAFT"; draft: Draft }
  | { type: "PROGRESS_PCT"; pct: number } // research completion bar
  | { type: "COMPLETE" }
  | { type: "ERROR"; message: string };

/* ─── Topic input ─────────────────────────────────────────────────────────── */

export interface TopicInput {
  topic: string; // "Dengue Surge — East Region"
  region: string; // "East Region"
  audience: string; // "Caregivers of elderly"
}
